title: Org Unit Sync
description: DHIS2 Organisation Unit Sync Documentation

remote_theme: just-the-docs/just-the-docs

search_enabled: true

aux_links:
  "GitHub Repository":
    - "https://github.com/priyanga76/dhis2-orgunit-sync"
