title: DHIS2 Org Unit Sync
description: Documentation and User Guide for the DHIS2 Org Unit Sync App

theme: jekyll-theme-cayman

header_pages:
  - quick-start.md
  - user-guide.md
  - troubleshooting.md
  - about.md

show_downloads: false

github:
  is_project_page: true
