site_name: DHIS2 Org Unit Sync Help
site_description: User documentation for the DHIS2 Org Unit Sync App
site_url: https://priyanga76.github.io/dhis2-orgunit-sync-docs/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight

nav:
  - Home: index.md
  - Quick Start: quick-start.md
  - User Guide: user-guide.md
  - Troubleshooting: troubleshooting.md
  - About: about.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
